import { useEffect, useState } from "react";
import { useAuth, useClerk, useUser } from "@clerk/react";
import { Link, Redirect, useLocation } from "wouter";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import * as api from "@workspace/api-client-react";
import { Activity, LayoutDashboard, CalendarDays, Users, Building2, Stethoscope, Settings, LogOut, ChevronRight, ArrowUpRight, Clock3, Check, Menu, QrCode, SlidersHorizontal, FileText, UserRound, Plus, X } from "lucide-react";
import { Logo } from "./App";
import { Editor, Empty, ErrorNotice, ResourcePage, resources, profileFields, settingsFields, title, today, allPages } from "./resources";

export function Onboarding(){
 const {isLoaded,isSignedIn}=useAuth(); const {user}=useUser();const [,navigate]=useLocation();const client=useQueryClient();
 const me=api.useGetMe({query:{queryKey:api.getGetMeQueryKey(),enabled:!!isSignedIn}});
 const onboard=api.useOnboard({mutation:{onSuccess:()=>{sessionStorage.removeItem("clinicflow-intent");client.invalidateQueries();}}});
 useEffect(()=>{if(me.data?.user&&!me.data.needsOnboarding){const role=me.data.user.role; const root=["superAdmin","clinicAdmin"].includes(role)?"admin":role;const reference=sessionStorage.getItem("clinicflow-qr");navigate(reference?`/book/${reference}`:`/${root}/dashboard`);}},[me.data,navigate]);
 if(!isLoaded||me.isLoading)return <div className="page-loading">Connecting your account…</div>;
 if(!isSignedIn)return <Redirect to="/login"/>;
 const intent=sessionStorage.getItem("clinicflow-intent")==="doctor"?"doctor":"patient";
 return <div className="onboarding"><Logo/><section className="panel"><span className="eyebrow">LET'S GET ACQUAINTED</span><h1>Welcome to your {intent==="doctor"?"practice":"care"} workspace.</h1><p>Complete your profile to get started. Your account is being registered as a {intent}.</p><ErrorNotice error={me.error||onboard.error}/><Editor initial={{fullName:user?.fullName||"",termsAccepted:false}} fields={[{key:"fullName",required:true},{key:"mobile",type:"tel"},{key:"termsAccepted",label:"I consent to the use of my information for appointment management",type:"checkbox",required:true}]} submitLabel="Complete my profile" busy={onboard.isPending} onSave={data=>onboard.mutate({data:{...data,intent}})}/></section></div>;
}
export function PublicBooking({reference}:{reference:string}){
 const auth=useAuth();const qr=api.useResolveQr(reference); const me=api.useGetMe({query:{queryKey:api.getGetMeQueryKey(),enabled:!!auth.isSignedIn}});
 useEffect(()=>{sessionStorage.setItem("clinicflow-qr",reference);},[reference]);
 if(qr.isLoading)return <div className="page-loading">Finding your clinic…</div>;
 return <div className="public-book"><Logo/><div className="panel"><span className="eyebrow">YOUR DIRECT LINK TO CARE</span><h1>{qr.data?.clinicName||"Book a visit"}</h1><ErrorNotice error={qr.error||me.error}/>{qr.data&&<><p>{[qr.data.branchName,qr.data.doctorName].filter(Boolean).join(" · ")}</p>{!auth.isSignedIn?<><p>Sign in securely to continue booking at this location.</p><Link className="button" href="/login">Sign in to book <ArrowUpRight size={18}/></Link></>:me.data?.needsOnboarding?<Redirect to="/onboarding"/>:me.data?.user?<Booking identity={me.data} context={qr.data}/>:<p>Loading your profile…</p>}</>}</div></div>;
}
const navConfig:Record<string,string[]>={
 admin:["dashboard","appointments","queue","clinics","branches","doctors","patients","users","qrs","reports","masters","audit","settings"],
 doctor:["dashboard","appointments","queue","patients","clinics","branches","availability","exceptions","qrs","profile"],
 receptionist:["dashboard","appointments","queue","patients"],
 patient:["dashboard","book","appointments","queue","profile"],
};
const labels:Record<string,string>={dashboard:"Overview",availability:"Weekly schedule",exceptions:"Date exceptions",qrs:"Booking QR codes",audit:"Audit log",book:"Book appointment",queue:"Live queue",masters:"Master data"};
const icons:Record<string,any>={dashboard:LayoutDashboard,appointments:CalendarDays,queue:Activity,clinics:Building2,branches:Building2,doctors:Stethoscope,patients:Users,users:Users,settings:Settings,reports:FileText,audit:FileText,availability:Clock3,exceptions:CalendarDays,qrs:QrCode,masters:SlidersHorizontal,profile:UserRound,book:Plus};
export function Portal({identity,role,page}:{identity:api.Identity;role:string;page:string}){
 const {signOut}=useClerk();const client=useQueryClient();const [open,setOpen]=useState(false);
 const name=identity.user!.fullName;
 const navigation=navConfig[role].filter(p=>identity.user!.role!=="clinicAdmin"||!["users","masters","settings","audit"].includes(p));
 return <div className="workspace"><aside className={`sidebar ${open?"open":""}`}><Logo/><div className="workspace-label">{role==="patient"?"YOUR CARE":"WORKSPACE"}<span>{title(role)}</span></div><nav>{navigation.map(p=>{const Icon=icons[p]||FileText;return <Link key={p} href={`/${role}/${p}`} className={p===page?"active":""} onClick={()=>setOpen(false)} data-testid={`nav-${p}`}><Icon size={19}/>{labels[p]||title(p)}{p===page&&<ChevronRight size={15}/>}</Link>;})}</nav><div className="sidebar-bottom"><div className="help-card"><span className="live-dot"/>Care, in sync.<p>Your workspace stays connected with live queue updates.</p></div><button className="logout" onClick={()=>{client.clear();signOut({redirectUrl:import.meta.env.BASE_URL});}} data-testid="button-signout"><LogOut size={18}/> Sign out</button></div></aside><div className="workspace-main"><header className="topbar"><button className="mobile-menu" onClick={()=>setOpen(!open)} aria-label="Toggle navigation"><Menu/></button><div className="breadcrumb">Workspace <ChevronRight size={13}/> <strong>{labels[page]||title(page)}</strong></div><div className="topbar-right"><span className="secure-label"><span className="live-dot"/> Secure workspace</span><span className="avatar">{name.split(" ").map(n=>n[0]).slice(0,2).join("")}</span><div><strong>{name}</strong><small>{title(identity.user!.role)}</small></div></div></header><main className="content"><div className="page-heading"><div><span className="eyebrow">{new Date().toLocaleDateString(undefined,{weekday:"long",month:"long",day:"numeric"})}</span><h1>{page==="dashboard"?`Good ${new Date().getHours()<12?"morning":new Date().getHours()<18?"afternoon":"evening"}, ${name.split(" ")[0]}.`:labels[page]||title(page)}</h1><p>{page==="dashboard"?"Here's what's happening with your care workspace today.":page==="queue"?"A clearer view of the day. Automatically refreshed every 30 seconds.":`Manage your ${labels[page]?.toLowerCase()||page} in one place.`}</p></div>{!["book","profile","settings"].includes(page)&&<Link className="button small" href={`/${role}/book`}><Plus size={17}/> Book appointment</Link>}</div>
 {page==="dashboard"?<Dashboard role={role}/>:page==="book"?<Booking identity={identity}/>:page==="appointments"?<Appointments/>:page==="queue"?<Queue identity={identity}/>:page==="profile"?<Profile identity={identity}/>:page==="settings"?<PlatformSettings/>:page==="reports"?<Reports/>:resources[page]?<ResourcePage key={page} resource={page} defaults={identity.doctorId?{doctorId:identity.doctorId,isOpen:true}:{}}/>:<Empty label="available modules"/>}
 <div className="content-footer"><span>ClinicFlow · Care, connected.</span><span>All times follow your clinic's configured timezone.</span></div></main></div></div>;
}
function Dashboard({role}:{role:string}){
 const q=api.useGetDashboard();
 return <><ErrorNotice error={q.error}/><div className="stat-grid">{[["Today's appointments",q.data?.todayAppointments,CalendarDays,"Scheduled for today"],["Waiting in queue",q.data?.waiting,Clock3,"Ready for their next step"],["Completed visits",q.data?.completed,Check,"Care delivered today"],["Average wait",q.data?.averageWaitMinutes,Activity,"Minutes, across today's visits"]].map(([label,value,Icon,caption]:any)=><div className="stat-card" key={label}><div><span>{label}</span><span className="stat-icon"><Icon size={19}/></span></div><strong>{q.isLoading?"…":value??"—"}</strong><small>{caption}</small></div>)}</div><div className="dashboard-grid"><section className="panel"><div className="panel-heading"><div><h2>{role==="patient"?"Your appointments":"Today's appointments"}</h2><p>A little clarity for the day ahead.</p></div><Link href={`/${role}/appointments`} className="text-link">View all <ChevronRight size={16}/></Link></div>{q.isLoading?<div className="skeleton">Loading appointments…</div>:q.data?.recentAppointments?.length?<AppointmentRows appointments={q.data.recentAppointments}/>:<Empty label="appointments"/>}</section><section className="care-card"><span className="eyebrow">MAKE ROOM FOR BETTER CARE</span><div className="care-card-icon"><CalendarDays size={42} strokeWidth={1.2}/></div><h2>{role==="patient"?"Your next visit starts here.":"A smoother day starts here."}</h2><p>{role==="patient"?"Choose your clinic and doctor, explore availability, and take the next step.":"Keep appointments organized and your patient flow moving, all from one workspace."}</p><Link className="button" href={`/${role}/book`}>Book an appointment <ArrowUpRight size={18}/></Link></section></div><section className="panel"><div className="panel-heading"><div><h2>Workspace activity</h2><p>The latest updates from your care network.</p></div><span className="badge">Live data</span></div>{q.data?.recentActivity?.length?<div className="activity-list">{q.data.recentActivity.map(a=><div key={a.id}><span className="icon-box"><Activity size={16}/></span><div><strong>{a.summary}</strong><small>{a.actorName} · {new Date(a.createdAt).toLocaleString()}</small></div></div>)}</div>:<Empty label="activity updates"/>}</section></>;
}
function AppointmentRows({appointments}:{appointments:api.Appointment[]}){
 const client=useQueryClient();const action=api.useTransitionAppointment({mutation:{onSuccess:()=>client.invalidateQueries()}});
 return <><ErrorNotice error={action.error}/><div className="table-scroll"><table><thead><tr><th>Patient / reference</th><th>Doctor & location</th><th>Date / token</th><th>Status</th><th>Next step</th></tr></thead><tbody>{appointments.map(a=><tr key={a.id} data-testid={`appointment-${a.id}`}><td><strong>{a.patientName}</strong><small>{a.reference}</small></td><td>{a.doctorName}<small>{a.clinicName} · {a.branchName}</small></td><td>{a.date}<small>Token {a.token}</small></td><td><span className={`badge ${a.status}`}>{title(a.status)}</span></td><td><div className="row-actions">{a.allowedActions.map(next=><button key={next} disabled={action.isPending} data-testid={`action-${next}-${a.id}`} onClick={()=>{let reason:string|undefined;if(next==="cancel"||next==="noShow"){const result=prompt("Please provide a reason");if(result===null)return;reason=result;}action.mutate({id:a.id,data:{action:next,expectedStatus:a.status,reason}});}}>{title(next)}</button>)}</div></td></tr>)}</tbody></table></div></>;
}
function Appointments(){
 const [search,setSearch]=useState("");const [date,setDate]=useState("");const [status,setStatus]=useState("");const [page,setPage]=useState(1);
 const q=api.useListAppointments({search,date:date||undefined,status:(status||undefined) as api.AppointmentStatus|undefined,page,pageSize:10},{query:{queryKey:api.getListAppointmentsQueryKey({search,date:date||undefined,status:(status||undefined) as api.AppointmentStatus|undefined,page,pageSize:10}),refetchInterval:30000}});
 return <><div className="toolbar filters"><input placeholder="Search patients or references…" value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}}/><input aria-label="Appointment date" type="date" value={date} onChange={e=>{setDate(e.target.value);setPage(1);}}/><select aria-label="Status" value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}}><option value="">All statuses</option>{Object.values(api.AppointmentStatus).map(s=><option key={s}>{s}</option>)}</select></div><ErrorNotice error={q.error}/><section className="panel">{q.isLoading?<div className="skeleton">Loading appointments…</div>:q.data?.items.length?<AppointmentRows appointments={q.data.items}/>:<Empty label="appointments"/>}<div className="pagination"><span>{q.data?.total??0} appointments</span><button disabled={page===1} onClick={()=>setPage(page-1)}>Previous</button><span>Page {page}</span><button disabled={page*10>=(q.data?.total??0)} onClick={()=>setPage(page+1)}>Next</button></div></section></>;
}
function SelectRecords({label,value,onChange,items,disabled=false}:{label:string;value:string;onChange:(s:string)=>void;items:any[];disabled?:boolean}){
 return <label>{label}<select value={value} disabled={disabled} onChange={e=>onChange(e.target.value)} data-testid={`select-${label.toLowerCase().replaceAll(" ","-")}`}><option value="">Select {label.toLowerCase()}…</option>{items.map(r=><option key={r.id} value={r.id}>{r.name||r.fullName}</option>)}</select></label>;
}
function Booking({identity,context}:{identity:api.Identity;context?:api.QrContext}){
 const [clinicId,setClinic]=useState(context?.clinicId||"");const [branchId,setBranch]=useState(context?.branchId||"");const [doctorId,setDoctor]=useState(context?.doctorId||"");const [date,setDate]=useState(today());const [step,setStep]=useState(1);const [patientId,setPatient]=useState(identity.patientId||"");const [consent,setConsent]=useState(false);const [notes,setNotes]=useState("");const [mobile,setMobile]=useState(identity.user?.mobile||"");const [code,setCode]=useState("");const [newPatient,setNewPatient]=useState(false);const [requestId]=useState(()=>crypto.randomUUID());
 const client=useQueryClient();const isPatient=identity.user?.role==="patient";
 const clinics=useQuery({queryKey:["booking-clinics"],queryFn:()=>allPages(api.listPublicClinics)});const branches=useQuery({queryKey:["booking-branches",clinicId],queryFn:()=>allPages(api.listPublicBranches,{clinicId:clinicId||undefined})});const doctors=useQuery({queryKey:["booking-doctors",clinicId,branchId],queryFn:()=>allPages(api.listPublicDoctors,{clinicId:clinicId||undefined,branchId:branchId||undefined})});
 const availableParams={doctorId,branchId,date};const availability=api.useGetPublicAvailability(availableParams,{query:{queryKey:api.getGetPublicAvailabilityQueryKey(availableParams),enabled:!!doctorId&&!!branchId&&!!date}});
 const patients=useQuery({queryKey:["booking-patients"],queryFn:()=>allPages(api.listPatients),enabled:!isPatient});
 const createPatient=api.useCreatePatient({mutation:{onSuccess:p=>{setPatient(p.id);setNewPatient(false);client.invalidateQueries();}}});
 const otp=api.useRequestOtp(); const verify=api.useVerifyOtp({mutation:{onSuccess:()=>client.invalidateQueries()}});
 const book=api.useCreateAppointment({mutation:{onSuccess:()=>{sessionStorage.removeItem("clinicflow-qr");client.invalidateQueries();}}});
 if(book.data)return <section className="panel confirmation"><span className="confirmation-check"><Check size={34}/></span><span className="eyebrow">YOU'RE BOOKED</span><h2>Your next step to better care.</h2><p>{book.data.doctorName} · {book.data.clinicName} · {book.data.branchName}</p><div className="confirmation-token"><small>YOUR TOKEN</small><strong>{book.data.token}</strong><span>{book.data.date}</span></div><p>Booking reference <strong>{book.data.reference}</strong></p><p className="notice">Booking and check-in are separate. Please check in at the clinic when you arrive.</p><Queue identity={identity} initial={book.data}/></section>;
 return <section className="panel booking-panel"><div className="booking-steps">{["Choose your care","Your details","Review & book"].map((s,i)=><div className={step===i+1?"active":step>i+1?"done":""} key={s}><span>{step>i+1?<Check size={15}/>:i+1}</span>{s}</div>)}</div><ErrorNotice error={clinics.error||branches.error||doctors.error||availability.error||book.error||patients.error}/>
 {step===1?<><div className="section-heading"><h2>Where would you like to visit?</h2><p>Choose from real clinics and available consulting sessions.</p></div><div className="form-grid"><SelectRecords label="Clinic" value={clinicId} disabled={!!context?.clinicId} onChange={v=>{setClinic(v);setBranch("");setDoctor("");}} items={clinics.data?.items||[]}/><SelectRecords label="Branch" value={branchId} disabled={!!context?.branchId||!clinicId} onChange={v=>{setBranch(v);setDoctor("");}} items={branches.data?.items||[]}/><SelectRecords label="Doctor" value={doctorId} disabled={!!context?.doctorId||!branchId} onChange={setDoctor} items={doctors.data?.items||[]}/><label>Visit date<input type="date" value={date} min={today()} onChange={e=>setDate(e.target.value)} data-testid="input-booking-date"/></label></div>{!clinics.isLoading&&!clinics.data?.items.length&&<Empty label="clinics accepting appointments"/>}{doctorId&&branchId&&<div className="availability-box">{availability.isLoading?"Checking availability…":availability.data?.available?<><span className="live-dot"/><strong>{availability.data.remainingTokens} places available</strong><p>{availability.data.startTime} – {availability.data.endTime} · {availability.data.timezone}{availability.data.breakStart&&` · Break ${availability.data.breakStart}–${availability.data.breakEnd}`}</p><small>Queue-based appointments. Your token is assigned when you book; an exact consultation time is not guaranteed.</small></>:<p>{availability.data?.reason||"No session is available on this date. Try another day."}</p>}</div>}<div className="form-footer"><button className="button" disabled={!availability.data?.available||availability.data.remainingTokens<1||availability.isFetching} onClick={()=>setStep(2)}>Continue <ChevronRight size={17}/></button></div></>:step===2?<><h2>Who is this visit for?</h2>{isPatient?<div className="notice">Booking for {identity.user?.fullName}. Your patient profile is securely linked to this account.</div>:<><SelectRecords label="Patient" value={patientId} onChange={setPatient} items={patients.data?.items||[]}/><button className="text-link" onClick={()=>setNewPatient(!newPatient)}><Plus size={16}/> Register a new patient</button>{newPatient&&<><ErrorNotice error={createPatient.error}/><Editor fields={resources.patients.fields} initial={{clinicId,branchId}} onSave={data=>createPatient.mutate({data})} busy={createPatient.isPending} submitLabel="Register patient"/></>}</>}
 {isPatient&&<div className="verification"><h3>Verify your mobile</h3><p>Mobile verification may be required by your clinic. International format, for example +14155552671.</p><div className="inline-form"><input type="tel" aria-label="Mobile number" value={mobile} onChange={e=>setMobile(e.target.value)}/><button disabled={otp.isPending||!mobile} onClick={()=>otp.mutate({data:{mobile}})}>Send code</button></div><ErrorNotice error={otp.error||verify.error}/>{otp.data&&<><p>Code sent via {otp.data.provider}. Expires at {new Date(otp.data.expiresAt).toLocaleTimeString()}.</p>{otp.data.developmentCode&&<p className="notice">Development-only verification code: <strong>{otp.data.developmentCode}</strong>. This is not a delivered SMS.</p>}<div className="inline-form"><input aria-label="Verification code" inputMode="numeric" value={code} onChange={e=>setCode(e.target.value)}/><button disabled={verify.isPending||!code} onClick={()=>verify.mutate({data:{challengeId:otp.data!.challengeId,code}})}>Verify</button></div></>}{verify.data?.verified&&<span className="badge active">Mobile verified</span>}</div>}
 <label>Notes for your visit<textarea maxLength={1000} value={notes} onChange={e=>setNotes(e.target.value)}/></label><div className="form-footer"><button onClick={()=>setStep(1)}>Back</button><button className="button" disabled={!patientId} onClick={()=>setStep(3)}>Review appointment <ChevronRight size={17}/></button></div></>:<><h2>Everything look right?</h2><div className="review-grid"><div><small>CLINIC & LOCATION</small><strong>{clinics.data?.items.find(c=>c.id===clinicId)?.name}</strong><p>{branches.data?.items.find(b=>b.id===branchId)?.name}</p></div><div><small>YOUR DOCTOR</small><strong>{doctors.data?.items.find(d=>d.id===doctorId)?.fullName}</strong><p>{date} · {availability.data?.startTime}–{availability.data?.endTime}</p></div><div><small>PATIENT</small><strong>{isPatient?identity.user?.fullName:patients.data?.items.find(p=>p.id===patientId)?.fullName}</strong></div></div><label className="check-label"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/> I consent to appointment management and the clinic's booking policy.</label><p className="notice">Your reservation is confirmed only after a token is issued. Availability is checked again when you confirm.</p><div className="form-footer"><button onClick={()=>setStep(2)}>Back</button><button className="button" disabled={!consent||book.isPending} data-testid="button-confirm-booking" onClick={()=>book.mutate({data:{clinicId,branchId,doctorId,patientId,date,source:context?"qr":isPatient?"online":"walkIn",qrReference:context?.reference,termsAccepted:consent,notes,requestId}})}>{book.isPending?"Confirming…":"Confirm appointment"} <Check size={17}/></button></div></>}
 </section>;
}
function Queue({identity,initial}:{identity:api.Identity;initial?:api.Appointment}){
 const [doctorId,setDoctor]=useState(initial?.doctorId||identity.doctorId||"");const [branchId,setBranch]=useState(initial?.branchId||"");const [date,setDate]=useState(initial?.date||today());const [appointmentId,setAppointment]=useState(initial?.id||"");const client=useQueryClient();const isPatient=identity.user?.role==="patient";
 const doctors=useQuery({queryKey:["queue-doctors"],queryFn:()=>allPages(api.listPublicDoctors)});const branches=useQuery({queryKey:["queue-branches"],queryFn:()=>allPages(api.listPublicBranches)});const appointments=useQuery({queryKey:["queue-appointments",date],queryFn:()=>allPages(api.listAppointments,{date}),enabled:isPatient});
 const params={doctorId,branchId,date,appointmentId:appointmentId||undefined};const queue=api.useGetQueue(params,{query:{queryKey:api.getGetQueueQueryKey(params),enabled:!!doctorId&&!!branchId,refetchInterval:30000}});
 const next=api.useCallNext({mutation:{onSuccess:()=>client.invalidateQueries()}});
 return <><div className="panel queue-filters"><div className="form-grid">{isPatient?<label>Your appointment<select value={appointmentId} onChange={e=>{const a=appointments.data?.items.find(a=>a.id===e.target.value);if(a){setAppointment(a.id);setDoctor(a.doctorId);setBranch(a.branchId);}}}><option value="">Select an appointment…</option>{appointments.data?.items.map(a=><option key={a.id} value={a.id}>{a.token} · {a.doctorName} · {a.branchName}</option>)}</select></label>:<><SelectRecords label="Doctor" value={doctorId} onChange={setDoctor} items={doctors.data?.items||[]}/><SelectRecords label="Branch" value={branchId} onChange={setBranch} items={branches.data?.items||[]}/></>}<label>Queue date<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label></div></div><ErrorNotice error={queue.error||next.error||appointments.error}/>{queue.isLoading&&doctorId&&branchId?<div className="skeleton">Updating live queue…</div>:queue.data?<><div className="queue-display"><div><span className="eyebrow">NOW SERVING</span><strong>{queue.data.currentToken||"—"}</strong><small>{queue.data.currentToken?"Consultation in progress":"No active consultation"}</small></div><div><span className="eyebrow">UP NEXT</span><strong>{queue.data.nextToken||"—"}</strong><small>{queue.data.waiting} waiting · {queue.data.completed} completed</small></div>{!isPatient&&<button className="button light" disabled={next.isPending} onClick={()=>next.mutate({data:{doctorId,branchId,date}})}>Call next patient <ChevronRight size={18}/></button>}</div>{queue.data.ownEntry&&<div className="notice"><h3>Your token: {queue.data.ownEntry.token}</h3><p>{queue.data.ownEntry.patientsAhead} patients ahead · Estimated wait {queue.data.ownEntry.estimatedWaitMinutes} minutes · {title(queue.data.ownEntry.status)}</p></div>}{queue.data.entries?.length?<section className="panel"><AppointmentRows appointments={queue.data.entries}/></section>:null}<p className="muted">Last updated {new Date(queue.data.updatedAt).toLocaleTimeString()} · Refreshes every 30 seconds</p></>:<Empty label="selected queue"/>}</>;
}
function Profile({identity}:{identity:api.Identity}){
 const client=useQueryClient();const doctor=api.useGetDoctor(identity.doctorId||"",{query:{queryKey:api.getGetDoctorQueryKey(identity.doctorId||""),enabled:!!identity.doctorId}});const patient=api.useGetPatient(identity.patientId||"",{query:{queryKey:api.getGetPatientQueryKey(identity.patientId||""),enabled:!!identity.patientId}});
 const mutation=useMutation<api.Patient|api.Doctor|api.User,Error,any>({mutationFn:(data:any)=>identity.doctorId?api.updateDoctor(identity.doctorId,data):identity.patientId?api.updatePatient(identity.patientId,data):api.updateMe(data),onSuccess:()=>client.invalidateQueries()});
 const data=identity.doctorId?doctor.data:identity.patientId?patient.data:identity.user;
 return <section className="panel padded"><h2>Your profile</h2><p className="muted">Keep your contact and care details up to date. Changing a mobile number resets its verification.</p><ErrorNotice error={doctor.error||patient.error||mutation.error}/>{mutation.isSuccess&&<p className="notice">Your profile has been saved.</p>}{data?<Editor key={JSON.stringify(data)} initial={data} fields={identity.doctorId?resources.doctors.fields.filter(f=>f.key!=="status"):identity.patientId?resources.patients.fields.filter(f=>!["clinicId","branchId","status"].includes(f.key)):profileFields} busy={mutation.isPending} onSave={d=>mutation.mutate(d)}/>:<p>Loading profile…</p>}</section>;
}
function PlatformSettings(){
 const q=api.useGetSettings();const client=useQueryClient();const mutation=api.useUpdateSettings({mutation:{onSuccess:()=>client.invalidateQueries()}});
 return <section className="panel padded"><h2>Platform preferences</h2><ErrorNotice error={q.error||mutation.error}/><div className="notice"><strong>Integration boundaries</strong><p>General notifications are not connected. Session timeout is managed by Clerk; platform preferences do not change your authentication session.</p><p>SMS provider: {q.data?.otpProviderConfigured?"Configured":"Not connected"} · Queue refresh: 30 seconds</p></div>{mutation.isSuccess&&<p className="notice">Settings saved.</p>}{q.data&&<Editor initial={q.data} fields={settingsFields} busy={mutation.isPending} onSave={data=>mutation.mutate({data})}/>}</section>;
}
function Reports(){
 const [from,setFrom]=useState(today());const [to,setTo]=useState(today());const [groupBy,setGroup]=useState<"date"|"clinic"|"doctor">("date");
 const q=api.useGetReports({from,to,groupBy});
 function download(){if(!q.data)return;const keys=["label","appointments","completed","cancelled","noShow","registrations","averageWaitMinutes"] as const;const csv=[keys.join(","),...q.data.rows.map(r=>keys.map(k=>`"${String(r[k]).replaceAll('"','""')}"`).join(","))].join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download="clinicflow-report.csv";a.click();URL.revokeObjectURL(a.href);}
 return <><div className="toolbar filters"><label>From<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>To<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><label>Group by<select value={groupBy} onChange={e=>setGroup(e.target.value as typeof groupBy)}><option value="date">Date</option><option value="clinic">Clinic</option><option value="doctor">Doctor</option></select></label><button onClick={download} disabled={!q.data?.rows.length}>Export CSV</button></div><ErrorNotice error={q.error}/><section className="panel"><div className="table-scroll"><table><thead><tr>{["Group","Appointments","Completed","Cancelled","No-show","Registrations","Average wait"].map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{q.data?.rows.map(r=><tr key={r.key}><td>{r.label}</td><td>{r.appointments}</td><td>{r.completed}</td><td>{r.cancelled}</td><td>{r.noShow}</td><td>{r.registrations}</td><td>{r.averageWaitMinutes} min</td></tr>)}</tbody></table></div>{!q.data?.rows.length&&<Empty label="report results"/>}</section></>;
}