import { Router, type IRouter } from "express";
import { geographyRouter } from "./geography";
import healthRouter from "./health";
import { identityRouter } from "./identity";
import { publicRouter } from "./public";
import { resourcesRouter } from "./resources";
import { appointmentsRouter } from "./appointments";
import { queueRouter } from "./queue";
import { reportingRouter } from "./reporting";
import otpRouter from "./otp";
import { appointmentQrRouter } from "./appointment-qr";
import { authRouter } from "./auth";
import { durationRouter } from "./duration";
import { guestRequestsRouter } from "./guest-requests";
import { clinicExpansionRouter } from "./clinic-expansion";
import { presenceRouter } from "./presence";
import { demoRouter } from "./demo";
import { integrationsRouter } from "./integrations";
import { notificationTemplatesRouter } from "./notification-templates";
import { permissionPolicyRouter } from "./permission-policy";
import { logosRouter } from "./logos";
import { systemUsersRouter } from "./system-users";
import { workspaceFeaturesRouter } from "./workspace-features";
import { patientRecordsRouter } from "./patient-records";

const router: IRouter = Router();
router.use(geographyRouter);
router.use(systemUsersRouter);

router.use(healthRouter);
router.use(clinicExpansionRouter);
router.use(presenceRouter);
router.use(publicRouter);
router.use(guestRequestsRouter);
router.use(authRouter);
router.use(demoRouter);
router.use(identityRouter);
router.use(otpRouter);
router.use(integrationsRouter);
router.use(notificationTemplatesRouter);
router.use(permissionPolicyRouter);
router.use(logosRouter);
router.use(workspaceFeaturesRouter);
router.use(patientRecordsRouter);
router.use(resourcesRouter);
router.use(durationRouter);
router.use(appointmentsRouter);
router.use(appointmentQrRouter);
router.use(queueRouter);
router.use(reportingRouter);

export default router;
