import { useState, type ReactNode } from "react";
import { useForm } from "react-hook-form";
import { Link } from "wouter";
import { Building2, Check, ChevronRight, Plus } from "lucide-react";
import { Logo } from "../App";
import { ClinicRegistrationHours, newWeek, validateWeek, type RegistrationDay } from "./ClinicRegistrationHours";
import "./clinic-registration.css";

export const publishedClinicBase = "https://clinic-flow-new-platform.replit.app";
export const normalizeClinicSlug = (value: string) => value.toLowerCase().normalize("NFKD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 63);
export type RegistrationBranch = { name: string; slug: string; address: string; city: string; timezone: string; email: string; phone: string; inheritEmail: boolean; inheritPhone: boolean; hours: RegistrationDay[] };
export type RegistrationValues = {
  fullName: string; email: string; mobile: string;
  name: string; slug: string; categoryId: string; specialityIds: string[]; referralCode: string; clinicEmail: string; phone: string;
  branches: RegistrationBranch[];
};
const newBranch = (): RegistrationBranch => ({ name: "", slug: "", address: "", city: "", timezone: Intl.DateTimeFormat().resolvedOptions().timeZone || "UTC", email: "", phone: "", inheritEmail: true, inheritPhone: true, hours: newWeek() });
type Option = { id: string; name: string };
type Props = { adminMode?: boolean; initial?: Partial<RegistrationValues>; categories: Option[]; specialities: Option[]; onSubmit: (values: RegistrationValues) => Promise<void>; checkSlug: (slug: string) => Promise<boolean>; busy: boolean; error?: string; referenceError?: string; finishSecurity?: ReactNode };
const steps = ["Clinic identity", "Locations", "Opening hours", "Care team", "Review"];

export function ClinicRegistrationWizard({ adminMode, initial, categories, specialities, onSubmit, checkSlug, busy, error, referenceError, finishSecurity }: Props) {
  const [step, setStep] = useState(0);
  const [validation, setValidation] = useState("");
  const [slugStatus, setSlugStatus] = useState<{ slug: string; available: boolean } | null>(null);
  const [checking, setChecking] = useState(false);
  const form = useForm<RegistrationValues>({ defaultValues: { fullName: "", email: "", mobile: "", name: "", slug: "", categoryId: "", specialityIds: [], referralCode: "", clinicEmail: "", phone: "", branches: [newBranch()], ...initial } });
  const values = form.watch();
  const set = form.setValue;
  const updateBranch = (index: number, patch: Partial<RegistrationBranch>) => set("branches", values.branches.map((b, i) => i === index ? { ...b, ...patch } : b), { shouldDirty: true });
  function validate(target: number) {
    if (target === 0 && (!values.name.trim() || !/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(values.slug) || values.slug.length < 3 || !values.fullName.trim() || !values.email.trim())) return "Complete the administrator name, email, clinic name and a valid public address (at least 3 characters).";
    if (target === 1 && values.branches.some(b => !b.name.trim() || !b.address.trim() || !/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(b.slug) || b.slug.length < 3 || !b.timezone.trim())) return "Each location needs a name, address, timezone and valid URL slug (at least 3 characters).";
    if (target === 1 && new Set(values.branches.map(b => b.slug)).size !== values.branches.length) return "Each location needs a different URL slug.";
    if (target === 2) for (const branch of values.branches) { const message = validateWeek(branch.hours); if (message) return `${branch.name}: ${message}`; }
    return "";
  }
  async function next() {
    setValidation("");
    const problem = validate(step);
    if (problem) return setValidation(problem);
    if (step === 0) {
      if (["doctor", "patient", "receptionist", "audit", "qrs", "exceptions", "health", "healthz", "robots", "sitemap"].includes(values.slug)) return setValidation("This address is reserved for the application. Choose a clinic-specific name.");
      setChecking(true);
      try { const available = await checkSlug(values.slug); setSlugStatus({ slug: values.slug, available }); if (!available) { setValidation("This clinic address is unavailable. Try adding your city or a distinctive clinic name."); return; } }
      catch (e) { setValidation(e instanceof Error ? e.message : "Could not check this address. Try again."); return; }
      finally { setChecking(false); }
    }
    setStep(s => s + 1);
  }
  async function finish() {
    for (let i = 0; i < steps.length - 1; i++) { const problem = validate(i); if (problem) { setValidation(problem); setStep(i); return; } }
    setValidation("");
    try { await onSubmit(values); } catch (e) { setValidation(e instanceof Error ? e.message : "Registration failed. Your changes remain here; please retry."); }
  }
  const field = (key: "fullName" | "email" | "mobile" | "name" | "referralCode" | "clinicEmail" | "phone", label: string, required = false, type = "text") => <label>{label}<input {...form.register(key)} required={required} type={type} data-testid={`registration-${key}`} readOnly={!adminMode && key === "email"}/></label>;
  return <div className="clinic-registration"><header className="registration-header"><Logo/><Link href={adminMode ? "/admin/users" : "/sign-in"} data-testid="registration-exit">Back to {adminMode ? "workspace" : "staff login"}</Link></header><div className="registration-layout"><aside className="registration-progress"><span className="eyebrow">REGISTER A CLINIC</span><h2>Built around your care.</h2><ol>{steps.map((label, i) => <li key={label} aria-current={step === i ? "step" : undefined}>{i < step ? <Check size={14}/> : `${i + 1}.`} {label}</li>)}</ol><small>Your setup stays in memory while this page is open. Nothing is saved until you finish. Passwords are handled only by secure account authentication.</small></aside><main className="registration-card"><span className="eyebrow">STEP {step + 1} OF {steps.length}</span><h1>{steps[step]}</h1><p>{["Give your clinic a home and a memorable public address.", "One clinic, one owner. Add each place where your team provides care.", "Set opening hours for every location. Doctor availability is managed separately.", "Bring your team in when you are ready.", "Check the details before creating your clinic."][step]}</p>{referenceError && <div className="error-box" role="alert">{referenceError}</div>}<form onSubmit={event => { event.preventDefault(); if (busy || checking) return; void (step === steps.length - 1 ? finish() : next()); }}>
    <fieldset disabled={busy || checking} style={{ border: 0, padding: 0, minWidth: 0 }}>
    {step === 0 && <div className="registration-fields">{field("fullName", "Administrator full name", true)}{field("email", "Administrator email", true, "email")}{adminMode && field("mobile", "Administrator phone", false, "tel")}{field("name", "Clinic name", true)}<label>Category<select {...form.register("categoryId")} data-testid="registration-category"><option value="">Select category (optional)</option>{categories.map(o => <option key={o.id} value={o.id}>{o.name}</option>)}</select></label>{field("clinicEmail", "Clinic email", false, "email")}{field("phone", "Clinic phone", false, "tel")}<label className="wide">Specialities<select multiple {...form.register("specialityIds")} data-testid="registration-specialities">{specialities.map(o => <option key={o.id} value={o.id}>{o.name}</option>)}</select><small className="registration-note">Optional. Select all services your clinic offers.</small></label>{field("referralCode", "Reference / referral code (optional)")}<label className="wide">Public clinic address<input value={values.slug} onChange={e => { set("slug", normalizeClinicSlug(e.target.value)); setSlugStatus(null); }} required minLength={3} maxLength={63} data-testid="registration-slug"/><button type="button" className="text-link" data-testid="registration-suggest-slug" onClick={() => { set("slug", normalizeClinicSlug(values.name)); setSlugStatus(null); }}>Suggest from clinic name</button></label><div className="registration-url wide"><strong>Published base address · read only</strong><br/>{publishedClinicBase}/<strong>{values.slug || "your-clinic"}</strong>{slugStatus?.slug === values.slug && <p role="status">{slugStatus.available ? "This address is currently available." : "This address is unavailable."}</p>}</div><p className="registration-note wide">Use lowercase letters, numbers and hyphens. Reserved application paths cannot be used. This address becomes permanent after registration; changing the clinic name will not change existing patient links.</p></div>}
    {step === 1 && <><div className="notice">Every branch has its own address. Email and phone inheritance are independent.</div>{values.branches.map((branch, index) => <details className="registration-branch" key={index} open><summary>{branch.name || `Location ${index + 1}`}</summary><div className="registration-fields">{(["name", "address", "city", "timezone", "slug"] as const).map(key => <label key={key}>{({name:"Location name",address:"Street address",city:"City",timezone:"Timezone",slug:"Location URL slug"})[key]}<input value={branch[key]} required={key !== "city"} data-testid={`registration-branch-${index}-${key}`} onChange={e => updateBranch(index, { [key]: key === "slug" ? normalizeClinicSlug(e.target.value) : e.target.value })}/>{key === "slug" && <button type="button" className="text-link" data-testid={`registration-branch-suggest-${index}`} onClick={() => updateBranch(index, { slug: normalizeClinicSlug(branch.name) })}>Suggest from location name</button>}</label>)}<label className="registration-check"><input type="checkbox" checked={branch.inheritEmail} data-testid={`registration-inherit-email-${index}`} onChange={e => updateBranch(index, { inheritEmail: e.target.checked })}/>Use clinic email</label>{!branch.inheritEmail && <label>Location email<input type="email" value={branch.email} data-testid={`registration-branch-email-${index}`} onChange={e => updateBranch(index, { email: e.target.value })}/></label>}<label className="registration-check"><input type="checkbox" checked={branch.inheritPhone} data-testid={`registration-inherit-phone-${index}`} onChange={e => updateBranch(index, { inheritPhone: e.target.checked })}/>Use clinic phone</label>{!branch.inheritPhone && <label>Location phone<input type="tel" value={branch.phone} data-testid={`registration-branch-phone-${index}`} onChange={e => updateBranch(index, { phone: e.target.value })}/></label>}</div>{values.branches.length > 1 && <button className="text-link" type="button" data-testid={`registration-remove-branch-${index}`} onClick={() => set("branches", values.branches.filter((_, i) => i !== index))}>Remove location</button>}</details>)}<button type="button" className="button secondary" data-testid="registration-add-branch" onClick={() => set("branches", [...values.branches, newBranch()])}><Plus size={16}/>Add another location</button></>}
    {step === 2 && values.branches.map((branch, index) => <details className="registration-branch" key={index} open={values.branches.length === 1 || undefined}><summary>{branch.name}</summary><ClinicRegistrationHours value={branch.hours} onChange={hours => updateBranch(index, { hours })}/></details>)}
    {step === 3 && <section className="registration-review"><div className="notice"><Building2 size={22}/><h3>Your clinic comes first. Your team can follow.</h3><p>Team invitations are optional. After registration, use Staff management to invite doctors and receptionists, choose their locations and track delivery. Existing invitation and password-setup security remains in place.</p><p>Consulting as a Clinic Admin is unavailable this release. Invite a doctor for clinical work; you can still manage clinic appointments and queues.</p><p>No invitations are sent from this step.</p></div></section>}
    {step === 4 && <div className="registration-review"><section><h3>{values.name}</h3><p>{values.clinicEmail || "No clinic email"} · {values.phone || "No clinic phone"}</p><p className="registration-url">{publishedClinicBase}/{values.slug}</p><p>Administrator: {values.fullName} · {values.email}</p></section>{values.branches.map((b, i) => <section key={i}><h3>{b.name}</h3><p>{b.address}{b.city ? `, ${b.city}` : ""}</p><p>{b.inheritEmail ? values.clinicEmail || "No clinic email" : b.email || "No location email"} · {b.inheritPhone ? values.phone || "No clinic phone" : b.phone || "No location phone"}</p><p>{b.hours.filter(d => d.isOpen).length} open days per week · {b.timezone}</p><small>/{values.slug}/{b.slug}</small></section>)}<section><h3>One owner, one account</h3><p>Clinic Admin account. Staff can be invited after setup. Consulting as a Clinic Admin is unavailable this release.</p></section><p className="registration-note">Finish saves the clinic setup together. The server rechecks ownership, URL availability and all details. Your public clinic and location addresses cannot be changed later.</p></div>}
    {step === 4 && finishSecurity}</fieldset>{(validation || error) && <div className="error-box" role="alert" data-testid="registration-error">{validation || error}</div>}<footer className="registration-footer"><button type="button" className="button secondary" disabled={step === 0 || busy || checking} data-testid="registration-back" onClick={() => { setValidation(""); setStep(s => s - 1); }}>Back</button><button className="button" disabled={busy || checking} data-testid="registration-next">{busy ? "Creating clinic…" : checking ? "Checking address…" : step === steps.length - 1 ? "Finish registration" : "Continue"}{!busy && <ChevronRight size={17}/>}</button></footer></form></main></div></div>;
}